<?php 

if(!empty($error)){
  foreach($error as $e){
?>
<br>
<div class="alert alert-danger">
<?php echo $e  ?>
</div>

<?php  }} ?>

<form action=<?= $this->url('user', ['action' => 'add']) ?> method="post" onsubmit="passValidator(event)">
<div class="form-group">
    <label for="name">Name:</label>
    <input required type="name" class="form-control" id="name" name="name">
  </div>
  <div class="form-group">
    <label for="email">Email address:</label>
    <input required type="email" class="form-control" id="email" name="email">
  </div>
  <div class="form-group">
    <label for="pwd">Password:</label>
    <input required type="password" class="form-control" id="pwd" name="pwd" minlength="6">
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>
<script>
function passValidator(event){
  let pass = document.querySelector("#pwd").value;
  if(pass.length<6){
    alert("password length should be greater than or equal to 6");
    event.preventDefault();
  }
}
</script>